preload = /home/taylor/Pictures/wallpapers/kayak.jpg
preload = /home/taylor/Pictures/wallpapers/house.jpg
preload = /home/taylor/Pictures/wallpapers/flower.jpg
preload = /home/taylor/Pictures/wallpapers/stairs.jpeg
preload = /home/taylor/Pictures/wallpapers/macos.jpg


wallpaper = eDP-1,/home/taylor/Pictures/wallpapers/stairs.jpeg
wallpaper = HDMI-A-1,~/Pictures/wallpapers/flower.jpg
wallpaper = DP-1,~/Pictures/wallpapers/flower.jpg
