#!/usr/bin/env bash

STATE=$(cat /proc/acpi/button/lid/LID0/state | awk '{print $2}')
MONITORS=$(hyprctl monitors | grep 'Monitor' | wc -l)

if [[ $STATE == "open" ]]; then
    hyprctl keyword monitor "eDP-1,2880x1920,0x0,1"
else
    if [[ $MONITORS -gt 1 ]]; then
        hyprctl keyword monitor "eDP-1,disable"
    fi
fi
