#!/bin/zsh
# Set your MySQL credentials
USER=""
PASSWORD=""
HOST=""

# Check if a query is passed as an argument
if [ -z "$1" ]; then
  echo "No query provided."
  echo "Usage: query \"SELECT * FROM Project WHERE id = 1;\""
  exit 1
fi
QUERY="$1"

# Execute the query using the MySQL command
mysql -u $USER -p$PASSWORD -h $HOST -e "$QUERY"
