#!/bin/bash
PROB=$1
echo problem: $PROB
[ -z "$PROB" ] && { echo 'Pick a problem name'; exit 1; }
[ ! -f "~/code/comp/$PROB/run.cpp" ] && cp ~/code/comp/problem_template.cpp ~/code/comp/$PROB/run.cpp
nvim + ~/code/comp/$PROB/run.cpp
